import unittest
import asyncio
import shutil
import os
from pydantic import BaseModel, Field
from ollama_wrapper.control import SQLiteRateLimiter
from ollama_wrapper.core import OllamaWrapper

# Test Pydantic Target Schema Guardrail
class MockExtractionSchema(BaseModel):
    extracted_topic: str = Field(description="The primary target subject identifier.")
    numeric_parameter: int = Field(description="Any extracted integer configuration values.")

class TestOllamaWrapperHardening(unittest.TestCase):

    def setUp(self):
        """Prepare isolated filesystem state for each test."""
        self.test_db_dir = "./tmp_test_vault"
        
    def tearDown(self):
        """Cleans up temporary disk database directory assets generated by tests."""
        if os.path.exists(self.test_db_dir):
            shutil.rmtree(self.test_db_dir)

    def test_instances_are_independent(self):
        """Ensures each constructor call creates an independent instance."""
        instance_1 = OllamaWrapper(connection_type="sync", llm_model="deepseek-r1:1.5b")
        instance_2 = OllamaWrapper(connection_type="async", llm_model="different-model:latest")

        self.assertIsNot(instance_1, instance_2)
        self.assertEqual(instance_1.connection_type, "sync")
        self.assertEqual(instance_2.connection_type, "async")

    def test_validation_invalid_connection_type(self):
        """Guarantees the driver throws clean parameter errors on invalid configuration strings."""
        with self.assertRaises(ValueError):
            OllamaWrapper(connection_type="invalid_mode_string")

    def test_validation_invalid_context_size(self):
        """Ensures context bounds checks intercept unstable, low rolling turn cap setups."""
        with self.assertRaises(ValueError):
            OllamaWrapper(max_active_turns=1)

    def test_edgecase_invalid_chunk_parameters(self):
        """Verifies boundary exception protection layers if text slicing overlap matches or exceeds chunk boundaries."""
        wrapper = OllamaWrapper(connection_type="sync")
        with self.assertRaises(ValueError):
            wrapper.ingest_knowledge_document("Valid document text fields strings.", chunk_size=100, overlap=100)

    def test_edgecase_empty_and_blank_ingestion(self):
        """Confirms that passing structural blanks or whitespace strings drops out gracefully without executing network layers."""
        wrapper = OllamaWrapper(connection_type="sync")
        wrapper.vector_database = []
        
        wrapper.ingest_knowledge_document("   ")
        wrapper.ingest_semantic_document("")
        
        self.assertEqual(len(wrapper.vector_database), 0)

    def test_edgecase_single_document_pool_normalization(self):
        """Tests that division-by-zero vectors don't cause crashes when single-item pools provide zero score delta ranges."""
        wrapper = OllamaWrapper(connection_type="sync")
        wrapper.vector_database = []
        
        # Seed only a single item into the database matrix
        wrapper.ingest_knowledge_document("Single isolated metric verification record document.")
        
        # FIXED BUG: Point to the unified hybrid retriever/reranker engine method name
        try:
            facts = wrapper._hybrid_retrieve_and_rerank("Is there anything here?")
            execution_success = True
        except ZeroDivisionError:
            execution_success = False
            
        self.assertTrue(execution_success)

    def test_cross_client_mode_cross_boundaries(self):
        """Guarantees cross-mode execution targets reject illegal synchronous actions while set to async modes."""
        wrapper = OllamaWrapper(connection_type="async")
        with self.assertRaises(RuntimeError):
            wrapper.ask("This request statement should bounce immediately.")

    def test_structured_schema_guardrail_ask(self):
        """Validates that passing Pydantic models returns native structured dictionary properties flawlessly."""
        wrapper = OllamaWrapper(connection_type="sync", llm_model="deepseek-r1:1.5b")
        
        wrapper.load_prompt_from_string("Extract content elements strictly.", optimize=False)
        wrapper.ingest_knowledge_document("System configurations logged output point directly to port number 8080.")
        
        result = wrapper.ask("What is the system configuration port value?", response_schema=MockExtractionSchema)
        
        self.assertIsInstance(result, MockExtractionSchema)
        self.assertTrue(hasattr(result, 'extracted_topic'))
        self.assertIsInstance(result.numeric_parameter, int)

    def test_choose_sqlite_rate_limiter_with_filename_only_path(self):
        wrapper = OllamaWrapper(connection_type="sync", db_storage_path=self.test_db_dir)
        prev_backend = os.environ.get("OLLAMA_WRAPPER_RATE_LIMIT_BACKEND")
        prev_db = os.environ.get("OLLAMA_WRAPPER_RATE_LIMIT_DB")
        db_file = "tmp_rate_limit_core_test.sqlite3"
        try:
            os.environ["OLLAMA_WRAPPER_RATE_LIMIT_BACKEND"] = "sqlite"
            os.environ["OLLAMA_WRAPPER_RATE_LIMIT_DB"] = db_file
            limiter = wrapper._choose_rate_limiter()
            self.assertIsInstance(limiter, SQLiteRateLimiter)
        finally:
            if prev_backend is None:
                os.environ.pop("OLLAMA_WRAPPER_RATE_LIMIT_BACKEND", None)
            else:
                os.environ["OLLAMA_WRAPPER_RATE_LIMIT_BACKEND"] = prev_backend
            if prev_db is None:
                os.environ.pop("OLLAMA_WRAPPER_RATE_LIMIT_DB", None)
            else:
                os.environ["OLLAMA_WRAPPER_RATE_LIMIT_DB"] = prev_db
            if os.path.exists(db_file):
                os.remove(db_file)

    def test_invalid_rate_limit_env_values_fall_back_to_defaults(self):
        wrapper = OllamaWrapper(connection_type="sync", db_storage_path=self.test_db_dir)
        prev_qps = os.environ.get("OLLAMA_WRAPPER_RATE_LIMIT_QPS")
        prev_burst = os.environ.get("OLLAMA_WRAPPER_RATE_LIMIT_BURST")
        prev_backend = os.environ.get("OLLAMA_WRAPPER_RATE_LIMIT_BACKEND")
        try:
            os.environ["OLLAMA_WRAPPER_RATE_LIMIT_BACKEND"] = "memory"
            os.environ["OLLAMA_WRAPPER_RATE_LIMIT_QPS"] = "not-a-float"
            os.environ["OLLAMA_WRAPPER_RATE_LIMIT_BURST"] = "not-an-int"
            limiter = wrapper._choose_rate_limiter()
            self.assertEqual(limiter.default_qps, 0.0)
            self.assertEqual(limiter.default_burst, 0)
        finally:
            if prev_qps is None:
                os.environ.pop("OLLAMA_WRAPPER_RATE_LIMIT_QPS", None)
            else:
                os.environ["OLLAMA_WRAPPER_RATE_LIMIT_QPS"] = prev_qps
            if prev_burst is None:
                os.environ.pop("OLLAMA_WRAPPER_RATE_LIMIT_BURST", None)
            else:
                os.environ["OLLAMA_WRAPPER_RATE_LIMIT_BURST"] = prev_burst
            if prev_backend is None:
                os.environ.pop("OLLAMA_WRAPPER_RATE_LIMIT_BACKEND", None)
            else:
                os.environ["OLLAMA_WRAPPER_RATE_LIMIT_BACKEND"] = prev_backend

    def test_close_stop_server_runs_teardown(self):
        class _DummyInstance:
            def __init__(self):
                self._api_server_task = object()
                self.stopped = False

            async def stop_api_server(self):
                self.stopped = True
                self._api_server_task = None

        dummy = _DummyInstance()
        OllamaWrapper.close(dummy, stop_server=True)
        self.assertTrue(dummy.stopped)
        self.assertIsNone(dummy._api_server_task)

    def test_unexpected_orchestrator_error_is_not_silently_swallowed(self):
        wrapper = OllamaWrapper(connection_type="sync", auto_ensure_ollama=False)
        wrapper.use_orchestrator_for_queries = True

        class _ExplodingOrchestrator:
            def run_query(self, request):
                _ = request
                raise TypeError("unexpected")

        wrapper._query_orchestrator = _ExplodingOrchestrator()
        with self.assertRaises(TypeError):
            wrapper.ask("hello")

class TestOllamaWrapperAsyncConcurrences(unittest.IsolatedAsyncioTestCase):

    async def test_concurrent_async_history_race_conditions(self):
        """
        Fires multiple queries at the exact same millisecond.
        The internal asyncio.Lock must prevent race conditions and maintain history integrity.
        """
        wrapper = OllamaWrapper(connection_type="async", max_active_turns=3)
        wrapper.load_prompt_from_string("You are an execution tracing assistant node.", optimize=False)
        
        task_1 = wrapper.ask_async("Identify task reference tag Alpha.")
        task_2 = wrapper.ask_async("Identify task reference tag Beta.")
        
        try:
            res_1, res_2 = await asyncio.gather(task_1, task_2)
            execution_stable = True
        except Exception as e:
            print(f"Concurrency step evaluation threw an unexpected mutation fault trace: {e}")
            execution_stable = False
            
        self.assertTrue(execution_stable)
        self.assertEqual(len(wrapper.chat_history), 2)

if __name__ == "__main__":
    unittest.main()